### ISSUE TITLE
squirrel --releasify

### ISSUE THREAD

**Issue by KevinCocquyt39** [Kibnet/Topshelf.Squirrel.Windows#1]
Hi,

Not an issue specifically related to the project but I was wondering what you use as the installer for your TopShelf service. I tried following the squirrel --releasify path but it creates a setup file which tries to install the packaged services as a .NET desktop app (for what Squirrel was originally created). So I'm not sure what type of files I should be creating. Would I need to just put my .exe and .dll's in a web folder (eg. http://.../releases)? Or what should I do actually?

Thanks in advance!

**Comment by Kibnet** [comment]
Hi, Kevin!
Squirrel implies the parallel existence of different versions in folders with the name of the version. I use it to have the ability to roll back when the new version fails. When you use "squirrel --releasify", you create nuget packages in the publication folder, and setup.exe for the initial installation. The service itself looks into the folder for new versions, pumps it out, unpacks it, launches the new version itself, and in case of successful launch of the new version in the end itself closes in.
If you do not need this, and you just need to put the files in a certain folder after the build, then I suggest writing a script that will simply copy the files to the destination folder with the replacement.
